### ISSUE TITLE
Cannot access example data

### ISSUE THREAD

**Issue by martinmodrak** [theislab/graph_abstraction#3]
I have problems with both minimal_examples and nestorowa. I also have problem running the analysis itself, so it is possible that my installation is corrupted (see #2), but the issues here seem orthogonal.

The minimal_examples.ipynb notebook fails when loading the required data
```... did not find original file <python-path>/python3.6/site-packages/scanpy/datasets/krumsiek11.txt```

as suggested, I also tried to run
```
sc.tl.sim('krumsiek11')
```

to recreate the dataset, but this fails with

```
<python-path>/python3.6/site-packages/scanpy/tools/sim.py in sim(model, tmax, branching, nrRealizations, noiseObs, noiseDyn, step, seed, writedir, read_params_from_file)
     75     if read_params_from_file:
     76         model_key = os.path.basename(model).replace('.txt', '')
---> 77         from .. import sim_models
     78         pfile_sim = os.path.dirname(sim_models.__file__) + '/' + model_key + '_params.txt'
     79         add_params = readwrite.read_params(pfile_sim)

ImportError: cannot import name 'sim_models'
```

For the nestorowa16.ipynb, I cannot load the file './data/nestorowa16/data_171011/nestorowa_corrected_log2_transformed_counts.txt' and although Readme.md gives a link to site with the original data, the original data do not work when substituted for the expected file - maybe some further preprocessing was done?

**Comment by falexwolf** [comment]
Sorry about all the issues! Scanpy's core underwent significant changes in the past week.

The issue with the datasets and the sim_models should be solved also when installing from PyPI: `pip install scanpy --upgrade`. If not, these do not appear when installing the now back to stable GitHub code.

We are working on providing the data for nestorowa16 in the same way it is as used here - sorry for that this takes so long. @fionahamey, could you please tell me how to exactly link to the files?

**Comment by falexwolf** [comment]
Hope this solves it https://github.com/theislab/scanpy/commit/e3afd9e41137dc5c49dd1afc4e21e4efb25080d0

I uploaded version 0.3.1 to PyPI for that.

**Comment by martinmodrak** [comment]
I confirm, that with the new version, in the minimal_examples notebook, both 
``` 
sc.tl.sim('krumsiek11')
```
and 
```
sc.datasets.krumsiek11()
```
seem to work correctly. Thanks for the fix.
