### ISSUE TITLE
"aga_groups" is invalid! in minimal_examples.ipynb

### ISSUE THREAD

**Issue by martinmodrak** [theislab/graph_abstraction#6]
When plotting the results in minimal_examples.ipynb, the code

```py
adata = sc.read('krumsiek11_blobs')
axs = sc.pl.aga(adata, basis='draw_graph_fr', color='aga_groups', groups_graph='aga_groups', right_margin=0.25,
                title='single-cell graph', save=True,
                root=[7, 10, 11], layout='rt',
                title_graph='abstracted graph')
```

results in

```pytb
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-06aed2f6a3c8> in <module>()
      3                 title='single-cell graph', save=True,
      4                 root=[7, 10, 11], layout='rt',
----> 5                 title_graph='abstracted graph')

~/anaconda3/envs/ga-pip/lib/python3.6/site-packages/scanpy/plotting/tools.py in aga(adata, basis, color, alpha, groups, components, projection, legend_loc, legend_fontsize, legend_fontweight, color_map, palette, size, title, right_margin, left_margin, show, save, ext, title_graph, groups_graph, color_graph, **aga_graph_params)
    472                 ax=axs[0],
    473                 show=False,
--> 474                 save=False)
    475     aga_graph(adata, ax=axs[1], show=False, save=False, title=title_graph,
    476               groups=groups_graph, color=color_graph, **aga_graph_params)

~/anaconda3/envs/ga-pip/lib/python3.6/site-packages/scanpy/plotting/tools.py in aga_scatter(adata, basis, color, alpha, groups, components, projection, legend_loc, legend_fontsize, legend_fontweight, color_map, palette, size, title, right_margin, show, save, ax)
    555                  title=title,
    556                  ax=ax,
--> 557                  show=False)
    558     utils.savefig_or_show('aga_' + basis, show=show, save=save)
    559     return ax

~/anaconda3/envs/ga-pip/lib/python3.6/site-packages/scanpy/plotting/ann_data.py in scatter(adata, x, y, color, alpha, basis, groups, components, projection, legend_loc, legend_fontsize, legend_fontweight, color_map, palette, right_margin, left_margin, size, title, show, save, ax)
    178                                  + ' specify valid sample annotation, one of '
    179                                  + str(adata.smp_keys()) + ' or a gene name '
--> 180                                  + str(adata.var_names))
    181             colorbars.append(True if continuous else False)
    182         if categorical: categoricals.append(ikey)

ValueError: "aga_groups" is invalid! specify valid sample annotation, one of ['X_diffmap0', 'louvain_groups', 'aga_pseudotime'] or a gene name ['Gata2' 'Gata1' 'Fog1' 'EKLF' 'Fli1' 'SCL' 'Cebpa' 'Pu.1' 'cJun' 'EgrNab'
 'Gfi1']

```

I also cannot run any of the cells below with various different errors - I am not sure, if those are independent of the results of this cell or not.

**Comment by falexwolf** [comment]
The "aga_groups" completely disappeared in Scanpy 0.3. They do not longer appear in the example notebooks, see, e.g.: https://github.com/theislab/graph_abstraction/blob/master/minimal_examples/minimal_examples.ipynb

Instead, we directly use the groups that have been passed using the `groups` parameter of `sc.tl.aga`.

Sorry, things like these usually don't happen; but the code and output now are much cleaner and simpler. In an early version, half a year ago, the "aga_groups" were still necessary...

Also your other problems will disappear then.

**Comment by martinmodrak** [comment]
Thanks for the quick reaction. Sorry, didn't realize I should update the example notebooks as well. Now everything seems to work (except for the ```eq_tree``` layout, but that's probably cool).

Also there seems to be minor issue with saving to PDF in the paul15 notebook:

```
axs = sc.pl.aga(adata, title='', threshold_dashed=0.01,
                basis='draw_graph_fr',
                root=5, show=False,
                pos='./write/aga_graph_gephi.gdf')
```

fails with a FileNotFoundError, but everything else works. Thanks a lot for help!

**Comment by falexwolf** [comment]
The comment above the line that you provide mentions that the graph drawing program Gephi has been used to adjust the layout of the nodes. The result has been saved to a 'gdf' file and is read in from file './write/aga_graph_gephi.gdf'. If this doesn't exist, then this throws a FileNotFoundError.

**Comment by martinmodrak** [comment]
I understand the cause, but the ```./write/aga_graph_gephi.gdf``` file is not created within the notebook, neither is it part of the Git repository and thus the paul15 notebook will not run to completion in current settings. Obviously I can skip the problematic cells (which I did). I just wanted to point out that this might be a minor issue you want to fix (it is of no consequence to me). 
Thanks for your time!

**Comment by falexwolf** [comment]
Yes, thank you! I will fix it.

Thank you for all your comments and patience!
