### ISSUE TITLE
Can't export diffusion map and aga figures as pdf

### ISSUE THREAD

**Issue by diazdc** [theislab/graph_abstraction#8]
Hi Alex, 

I'm trying to export a diffusion map plot as a pdf, but the function keeps defaulting to a png. The resulting file name is "diffmap_components123my_3Dplot.pdf.png".

`rcParams['figure.figsize'] = (10, 10)
sc.pl.diffmap(adata_corrected,
              color = 'louvain_groups',
              projection = '3d',
              save = "my_3Dplot.pdf")
sc.pl.reset_rcParams()`

I'm also experiencing the same problem with the abstracted graph:

`rcParams['figure.figsize'] = (5, 5)
sc.pl.aga_graph(adata_corrected,
frameon = True,
title = 'abstracted graph and lineage tree',
root = '1',
layout = 'rt_circular',
node_size_scale = 0.4,
node_size_power = 0.7,
max_edge_width = 0.7,
fontsize = 5,
return_pos = True,
save = 'aga_plot_.pdf')
sc.pl.reset_rcParams()`

What's interesting, however, is that both the tSNE plot and the tSNE/aga plot export as a pdf just fine:

`rcParams['figure.figsize'] = (5, 5)
sc.pl.tsne(adata_corrected, size=10,
legend_fontsize=12, legend_fontweight='bold',
                 color='louvain_groups',
                 legend_loc='on data',
                 title = 'Louvain Clusters',
                 save = 'louvain_groups.pdf')
sc.pl.reset_rcParams()`

`rcParams['figure.figsize'] = (5, 5)
sc.pl.aga(adata_corrected, save = '_.pdf')
sc.pl.reset_rcParams()`

Thanks!

**Comment by diazdc** [comment]
Apologies. I was still using scanpy v0.3. Everything works fine now after updating to 0.4.

**Comment by falexwolf** [comment]
Good to hear, sorry for the late replies... I have become the father of twins in the past weeks... Will respond sooner in the future again.

**Comment by diazdc** [comment]
Congrats on the twins!! Thanks for getting back to me.
